"""Markdown report generator."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Template

from ..definition.scan_result import ScanResult
from ..definition.analysis import AnalysisResult
from ..definition.suggestion import AIAnalysis


REPORT_TEMPLATE = """# File Organization Report

Generated: {{ generated_at }}

---

## Scan Summary

| Metric | Value |
|--------|-------|
| Total Files | {{ summary.total_files }} |
| Total Directories | {{ summary.total_directories }} |
| Total Size | {{ summary.total_size_human }} |
| Empty Directories | {{ summary.empty_directories }} |
| Scan Duration | {{ "%.1f"|format(summary.scan_duration_seconds) }}s |

## File Type Distribution

| Extension | Count | Size |
|-----------|-------|------|
{% for ft in summary.file_types[:15] -%}
| {{ ft.extension }} | {{ ft.count }} | {{ ft.total_size_human }} |
{% endfor %}

---

## Issues Detected

{% if analysis.has_issues %}
### Summary

| Issue Type | Count | Impact |
|------------|-------|--------|
{% if analysis.duplicates -%}
| Duplicate Files | {{ analysis.duplicates|length }} groups | Wasting {{ wasted_by_duplicates }} |
{% endif -%}
{% if analysis.large_files -%}
| Large Files (>100MB) | {{ analysis.large_files|length }} | {{ large_files_size }} total |
{% endif -%}
{% if analysis.stale_files -%}
| Stale Files (>180 days) | {{ analysis.stale_files|length }} | {{ stale_files_size }} total |
{% endif -%}
{% if analysis.empty_directories -%}
| Empty Directories | {{ analysis.empty_directories|length }} | Clutter |
{% endif %}

{% if analysis.duplicates %}
### Duplicate Files

{% for dup in analysis.duplicates[:10] %}
**Group {{ loop.index }}** ({{ dup.count }} files, {{ dup.wasted_human }} wasted)
{% for path in dup.files[:5] %}
- `{{ path }}`
{% endfor %}
{% if dup.files|length > 5 %}
- ... and {{ dup.files|length - 5 }} more
{% endif %}

{% endfor %}
{% endif %}

{% if analysis.large_files %}
### Large Files

| File | Size | Last Modified |
|------|------|---------------|
{% for f in analysis.large_files[:10] %}
| `{{ f.path.name }}` | {{ f.size_human }} | {{ f.modified_at.strftime("%Y-%m-%d") }} |
{% endfor %}
{% if analysis.large_files|length > 10 %}
*... and {{ analysis.large_files|length - 10 }} more*
{% endif %}
{% endif %}

{% if analysis.stale_files %}
### Stale Files (Not Accessed in 180+ Days)

Top 10 by staleness:

| File | Days Stale | Size |
|------|------------|------|
{% for f in analysis.stale_files[:10] %}
| `{{ f.path.name }}` | {{ f.days_stale }} days | {{ f.size_human }} |
{% endfor %}
{% if analysis.stale_files|length > 10 %}
*... and {{ analysis.stale_files|length - 10 }} more*
{% endif %}
{% endif %}

{% else %}
No issues detected! Your files are well organized.
{% endif %}

---

{% if ai_analysis %}
## AI Analysis

### Work Pattern

{{ ai_analysis.work_pattern.activity_description }}

{% if ai_analysis.work_pattern.peak_hours %}
- Peak Hours: {{ ai_analysis.work_pattern.peak_hours|join(", ") }}:00
{% endif %}
{% if ai_analysis.work_pattern.peak_days %}
- Peak Days: {{ ai_analysis.work_pattern.peak_days|join(", ") }}
{% endif %}

### File Habits

- Most Used Types: {{ ai_analysis.file_habit.most_used_types|join(", ") or "N/A" }}
- Naming Style: {{ ai_analysis.file_habit.naming_style or "N/A" }}
- Organization Score: {{ ai_analysis.file_habit.organization_score }}/100

### Personality Insight

**Chaos Level:** {{ ai_analysis.personality_insight.chaos_level }}

**Strengths:**
{% for s in ai_analysis.personality_insight.strengths %}
- {{ s }}
{% endfor %}

**Challenges:**
{% for c in ai_analysis.personality_insight.challenges %}
- {{ c }}
{% endfor %}

### Suggestions

{% for s in ai_analysis.suggestions %}
#### {{ loop.index }}. {{ s.title }} [{{ s.priority }}]

*Category: {{ s.category }}*

{{ s.description }}

**Benefit:** {{ s.estimated_benefit }}

{% endfor %}

### Summary

{{ ai_analysis.summary }}

---

## Your Gains

{{ ai_analysis.gains }}

---

## Encouragement

> {{ ai_analysis.encouragement }}

{% endif %}

---

*Report generated by FileOrganizer v0.1.0*
"""


def generate_markdown_report(
    scan_result: ScanResult,
    analysis_result: AnalysisResult,
    ai_analysis: Optional[AIAnalysis] = None,
    output_path: Optional[Path] = None,
) -> str:
    """Generate a Markdown report.

    Args:
        scan_result: The scan result.
        analysis_result: The analysis result.
        ai_analysis: Optional AI analysis.
        output_path: Optional path to save the report.

    Returns:
        The generated Markdown content.
    """
    template = Template(REPORT_TEMPLATE)

    # Helper functions for formatting
    def format_size(size_bytes: int) -> str:
        size = float(size_bytes)
        for unit in ["B", "KB", "MB", "GB", "TB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} PB"

    content = template.render(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        summary=scan_result.summary,
        analysis=analysis_result,
        ai_analysis=ai_analysis,
        wasted_by_duplicates=format_size(analysis_result.total_wasted_by_duplicates),
        large_files_size=format_size(analysis_result.total_large_files_size),
        stale_files_size=format_size(analysis_result.total_stale_files_size),
    )

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")

    return content
